import {parseM3U} from './src/m3u.js';
import {testXtream, importXtream} from './src/xtream.js';
import {getMDBListItems, matchMDBListToCatalog} from './src/mdblist.js';
import {loadState, saveState, clearState} from './src/storage.js';
import {demoCatalog} from './src/demo.js';

const DEFAULT_STATE={page:'home', catalog:[], provider:null, favourites:[], continueWatching:[], mdblistRows:[], settings:{mdblistApiKey:''}};
const state=Object.assign({},DEFAULT_STATE,loadState()||{});
let modal=null, toastTimer=null;
const $app=document.querySelector('#app');

function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function activeCatalog(){return state.catalog.length?state.catalog:demoCatalog}
function items(kind){return activeCatalog().filter(x=>x.kind===kind)}
function card(item,poster=false,opts={}){
  const bg=item.logo?`url('${esc(item.logo)}') center/cover`:item.demoColor||`linear-gradient(135deg,hsl(${Math.abs(hash(item.name))%360} 42% 38%),#0e1526)`;
  const sub=item.kind==='live'?(item.group||'Live TV'):[item.year,item.rating?`★ ${item.rating}`:''].filter(Boolean).join('  ·  ');
  return `<button class="card ${poster?'poster':''}" data-play="${esc(item.id)}" style="--card-bg:${bg}" aria-label="${esc(item.name)}">
    <div class="card-bg"></div>${item.kind==='live'?`<div class="badge"><span class="live-dot"></span>LIVE</div>`:''}
    <div class="card-copy"><div class="card-title">${esc(item.name)}</div><div class="card-sub">${esc(sub)}</div></div>
    ${opts.progress?`<div class="progress"><i style="width:${opts.progress}%"></i></div>`:''}</button>`;
}
function hash(s=''){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h)+s.charCodeAt(i)|0;return h}
function nav(){const pages=[['home','⌂','Home'],['live','◉','Live TV'],['movies','▰','Movies'],['series','▦','TV Shows'],['search','⌕','Search']];return `
  <header class="topbar"><div class="brand"><i class="brand-mark"></i>SWOOP TV</div>
  <nav class="desktop-nav">${pages.map(([p,,label])=>`<button class="nav-btn ${state.page===p?'active':''}" data-page="${p}">${label}</button>`).join('')}</nav>
  <div class="top-actions"><button class="icon-btn" data-page="search" aria-label="Search">⌕</button><button class="icon-btn" data-modal="provider"><span class="label-hide">＋ Provider</span></button><button class="icon-btn" data-page="settings" aria-label="Settings">⚙</button></div></header>
  <nav class="bottom-nav">${pages.map(([p,icon,label])=>`<button class="${state.page===p?'active':''}" data-page="${p}"><span>${icon}</span>${label}</button>`).join('')}</nav>`}
function rail(title,data,poster=false,meta=''){if(!data.length)return'';return `<section class="section"><div class="section-head"><h2>${esc(title)}</h2><span class="section-meta">${esc(meta)}</span></div><div class="rail">${data.map((x,i)=>card(x,poster,{progress:title==='Continue Watching'?(28+i*11)%86:0})).join('')}</div></section>`}
function home(){
  const cat=activeCatalog(), live=cat.filter(x=>x.kind==='live'), movies=cat.filter(x=>x.kind==='movie'), shows=cat.filter(x=>x.kind==='series');
  const providerName=state.provider?.name||'Demo Library';
  return `<main><section class="hero"><div class="hero-art"></div><div class="hero-content"><div class="eyebrow">${state.catalog.length?'YOUR LIBRARY IS READY':'SWOOP TV v0.1'}</div><h1>Your TV.<br>Your way.</h1><p>${state.catalog.length?`${esc(providerName)} is connected. Browse live channels, movies and series from one cinematic interface.`:'Connect an M3U playlist or Xtream provider to replace this demo catalog with your own authorised TV library.'}</p><div class="cta-row"><button class="btn accent" data-modal="provider">${state.catalog.length?'Manage Provider':'Add TV Provider'}</button><button class="btn secondary" data-page="live">Open Live TV</button></div></div></section>
  <div class="content">${rail('Live Now',live.slice(0,12),false,`${live.length} channels`)}${rail('Continue Watching',[...movies,...shows].slice(0,8),true)}${state.mdblistRows.map(r=>rail(r.name,r.items,true,`${r.items.length} available`)).join('')}${rail('Movies',[...movies].slice(0,12),true,`${movies.length} titles`)}${rail('TV Shows',[...shows].slice(0,12),true,`${shows.length} series`)}</div></main>`;
}
function page(kind,title){const arr=items(kind);return `<main class="page"><div class="page-title-row"><div><h1>${title}</h1><div class="subtle">${state.catalog.length?`${arr.length} items from ${esc(state.provider?.name||'your provider')}`:'Demo content — connect a provider to populate your library.'}</div></div><button class="btn secondary" data-modal="provider">＋ Provider</button></div>${arr.length?`<div class="${kind==='live'?'channel-grid':'grid'}">${kind==='live'?arr.map((x,i)=>`<button class="channel-card" data-play="${esc(x.id)}"><div class="channel-logo">${esc((x.name||'?').slice(0,2).toUpperCase())}</div><div><div class="channel-now">${esc(x.name)}</div><div class="channel-next">${esc(x.group||'Live TV')} · Now playing</div></div><div class="channel-num">${String(i+1).padStart(3,'0')}</div></button>`).join(''):arr.map(x=>card(x,true)).join('')}</div>`:empty('No content yet','Connect a TV provider to populate this section.')}</main>`}
function empty(title,copy){return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(copy)}</p><button class="btn accent" data-modal="provider">Add TV Provider</button></div>`}
function searchPage(){return `<main class="page"><div class="page-title-row"><div><h1>Search</h1><div class="subtle">Search channels, movies and TV shows.</div></div><div class="searchbox"><input id="searchInput" autofocus placeholder="Search Swoop TV…" /></div></div><div id="searchResults" class="grid"></div></main>`}
function settingsPage(){const counts={live:items('live').length,movie:items('movie').length,series:items('series').length};return `<main class="page"><div class="page-title-row"><div><h1>Settings</h1><div class="subtle">Provider, discovery and local-device configuration.</div></div></div><div class="settings-list">
  <section class="setting-card"><h3>Provider</h3><div class="kv"><span>Connected source</span><span>${esc(state.provider?.name||'Demo mode')}</span></div><div class="kv"><span>Catalog</span><span>${counts.live} live · ${counts.movie} movies · ${counts.series} series</span></div><div class="cta-row"><button class="btn secondary" data-modal="provider">Manage provider</button>${state.catalog.length?'<button class="btn danger" data-action="disconnect">Disconnect</button>':''}</div></section>
  <section class="setting-card"><h3>MDBList discovery rows</h3><p class="form-hint">Connect an MDBList API key and list to create a Swoop TV row containing only titles that also exist in your imported catalog.</p><div class="cta-row"><button class="btn secondary" data-modal="mdblist">Add MDBList row</button></div>${state.mdblistRows.length?state.mdblistRows.map((r,i)=>`<div class="kv"><span>${esc(r.name)}</span><span>${r.items.length} matched · <button class="nav-btn" data-remove-row="${i}">Remove</button></span></div>`).join(''):''}</section>
  <section class="setting-card"><h3>Privacy & playback architecture</h3><p class="form-hint">Swoop TV does not bundle content. Imported stream URLs play directly from your provider whenever the browser/device supports them. Provider credentials are not retained unless you explicitly enable “Remember provider” during import.</p></section>
  </div></main>`}
function render(){let body;if(state.page==='home')body=home();else if(state.page==='live')body=page('live','Live TV');else if(state.page==='movies')body=page('movie','Movies');else if(state.page==='series')body=page('series','TV Shows');else if(state.page==='search')body=searchPage();else body=settingsPage();$app.innerHTML=`<div class="app-shell">${nav()}${body}${modal?modalHtml():''}</div>`;bind();if(state.page==='search')runSearch('')}
function providerModal(){return `<div class="modal-backdrop" data-close-modal><div class="modal" data-modal-card><div class="modal-head"><h2>Add TV Provider</h2><button class="icon-btn" data-close>✕</button></div><div class="modal-body"><div class="tabs"><button class="active" data-provider-tab="m3u">M3U Playlist</button><button data-provider-tab="xtream">Xtream</button></div>
  <form id="m3uForm" class="form-grid"><div class="field"><label>Provider name</label><input name="name" value="My TV" required></div><div class="field"><label>M3U playlist URL</label><input name="url" type="url" placeholder="https://provider.example/playlist.m3u"></div><div class="field"><label>Or choose an M3U file</label><input name="file" type="file" accept=".m3u,.m3u8,text/plain,application/x-mpegURL"></div><div class="field"><label>Optional XMLTV / EPG URL</label><input name="epgUrl" type="url" placeholder="https://provider.example/epg.xml"></div><p class="form-hint">Browser imports require the playlist server to allow cross-origin requests. Local M3U files work without CORS.</p><button class="btn accent" type="submit">Import M3U</button></form>
  <form id="xtreamForm" class="form-grid" hidden><div class="field"><label>Provider name</label><input name="name" value="My TV" required></div><div class="field"><label>Server URL</label><input name="server" type="url" placeholder="https://provider.example:port" required></div><div class="split"><div class="field"><label>Username</label><input name="username" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div></div><label class="form-hint"><input type="checkbox" name="remember"> Remember provider credentials on this device (stored in browser storage, not encrypted).</label><p class="form-hint">Swoop TV will read catalog metadata from the provider API. Video streams are not proxied through Swoop TV.</p><button class="btn accent" type="submit">Connect Xtream</button></form><div id="providerStatus"></div></div></div></div>`}
function mdblistModal(){return `<div class="modal-backdrop" data-close-modal><div class="modal" data-modal-card><div class="modal-head"><h2>Add MDBList Row</h2><button class="icon-btn" data-close>✕</button></div><div class="modal-body"><form id="mdblistForm" class="form-grid"><div class="field"><label>Row name in Swoop TV</label><input name="rowName" value="My MDBList" required></div><div class="field"><label>MDBList API key</label><input name="apiKey" type="password" value="${esc(state.settings.mdblistApiKey||'')}" required></div><div class="field"><label>List ID</label><input name="listId" placeholder="e.g. 12345"></div><div class="divider"></div><p class="form-hint">Or identify the list by username + list slug/name.</p><div class="split"><div class="field"><label>Username</label><input name="username" placeholder="username"></div><div class="field"><label>List name / slug</label><input name="listName" placeholder="best-action-movies"></div></div><button class="btn accent" type="submit">Fetch & Match Catalog</button></form><div id="mdbStatus"></div></div></div></div>`}
function modalHtml(){return modal==='provider'?providerModal():mdblistModal()}
function setStatus(id,msg,type='info'){const el=document.querySelector(id);if(el)el.innerHTML=`<div class="status ${type}">${esc(msg)}</div>`}
function toast(msg){clearTimeout(toastTimer);document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);toastTimer=setTimeout(()=>el.remove(),2200)}
function findItem(id){return activeCatalog().find(x=>x.id===id)}
function play(item){if(!item)return;if(!item.streamUrl){toast(item.source==='demo'?'Demo item — connect your provider for playback.':item.kind==='series'?'Series episode loading comes in the playback/EPG pass.':'No playable URL available.');return;}const win=window.open('','_blank');if(!win){toast('Pop-up blocked.');return}const safe=esc(item.streamUrl);win.document.write(`<!doctype html><meta name="viewport" content="width=device-width"><title>${esc(item.name)}</title><style>html,body{margin:0;background:#000;height:100%;display:grid;place-items:center}video{width:100%;height:100%;max-height:100vh;background:#000}</style><video src="${safe}" controls autoplay playsinline></video>`)}
function runSearch(q){const out=document.querySelector('#searchResults');if(!out)return;const term=q.trim().toLowerCase();const res=term?activeCatalog().filter(x=>`${x.name} ${x.group}`.toLowerCase().includes(term)).slice(0,80):activeCatalog().slice(0,24);out.innerHTML=res.length?res.map(x=>card(x,x.kind!=='live')).join(''):empty('No matches','Try another title, channel or category.')}
function persist(){saveState({...state,page:'home'})}
function bind(){
  document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>{state.page=el.dataset.page;render()});
  document.querySelectorAll('[data-modal]').forEach(el=>el.onclick=()=>{modal=el.dataset.modal;render()});
  document.querySelectorAll('[data-close]').forEach(el=>el.onclick=()=>{modal=null;render()});
  document.querySelectorAll('[data-close-modal]').forEach(el=>el.onclick=e=>{if(e.target===el){modal=null;render()}});
  document.querySelectorAll('[data-play]').forEach(el=>el.onclick=()=>play(findItem(el.dataset.play)));
  document.querySelector('[data-action="disconnect"]')?.addEventListener('click',()=>{state.catalog=[];state.provider=null;state.mdblistRows=[];clearState();render();toast('Provider disconnected');});
  document.querySelectorAll('[data-remove-row]').forEach(el=>el.onclick=()=>{state.mdblistRows.splice(Number(el.dataset.removeRow),1);persist();render()});
  const search=document.querySelector('#searchInput');if(search)search.oninput=e=>runSearch(e.target.value);
  document.querySelectorAll('[data-provider-tab]').forEach(el=>el.onclick=()=>{document.querySelectorAll('[data-provider-tab]').forEach(x=>x.classList.toggle('active',x===el));document.querySelector('#m3uForm').hidden=el.dataset.providerTab!=='m3u';document.querySelector('#xtreamForm').hidden=el.dataset.providerTab!=='xtream';});
  document.querySelector('#m3uForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),file=fd.get('file'),url=String(fd.get('url')||'').trim();try{setStatus('#providerStatus','Reading playlist…');let text;if(file&&file.size)text=await file.text();else if(url){const r=await fetch(url);if(!r.ok)throw new Error(`Playlist returned HTTP ${r.status}`);text=await r.text()}else throw new Error('Choose an M3U file or enter a playlist URL.');const providerId=`m3u-${Date.now()}`,cat=parseM3U(text,providerId);if(!cat.length)throw new Error('No playable entries were found in that M3U playlist.');state.catalog=cat;state.provider={id:providerId,type:'m3u',name:String(fd.get('name')||'M3U Provider'),epgUrl:String(fd.get('epgUrl')||'')};state.mdblistRows=[];persist();setStatus('#providerStatus',`Imported ${cat.length} items. Opening Swoop TV…`,'ok');setTimeout(()=>{modal=null;state.page='home';render();},500)}catch(err){setStatus('#providerStatus',err.message||String(err),'err')}});
  document.querySelector('#xtreamForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),cfg={server:String(fd.get('server')),username:String(fd.get('username')),password:String(fd.get('password'))};try{setStatus('#providerStatus','Testing Xtream account…');const profile=await testXtream(cfg);if(profile?.user_info?.auth===0)throw new Error('Xtream account was not authorised.');setStatus('#providerStatus','Connected. Importing live TV, movies and series…');const providerId=`xtream-${Date.now()}`;const result=await importXtream(cfg,providerId);if(!result.items.length)throw new Error('Connected, but the provider returned an empty catalog.');state.catalog=result.items;state.provider={id:providerId,type:'xtream',name:String(fd.get('name')||'Xtream Provider'), ...(fd.get('remember')?cfg:{server:cfg.server})};state.mdblistRows=[];persist();setStatus('#providerStatus',`Imported ${result.items.length} items. Opening Swoop TV…`,'ok');setTimeout(()=>{modal=null;state.page='home';render();},500)}catch(err){setStatus('#providerStatus',`${err.message||err}. If the login works in another IPTV app, browser CORS may be blocking the provider API.`,'err')}});
  document.querySelector('#mdblistForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!state.catalog.length){setStatus('#mdbStatus','Import an IPTV catalog first so Swoop TV has something to match against.','err');return}const fd=new FormData(e.currentTarget),apiKey=String(fd.get('apiKey')||'').trim();try{setStatus('#mdbStatus','Fetching MDBList and matching it against your provider catalog…');const payload=await getMDBListItems({apiKey,listId:String(fd.get('listId')||'').trim(),username:String(fd.get('username')||'').trim(),listName:String(fd.get('listName')||'').trim()});const matched=matchMDBListToCatalog(payload,state.catalog);state.settings.mdblistApiKey=apiKey;state.mdblistRows.push({name:String(fd.get('rowName')||'MDBList'),items:matched});persist();setStatus('#mdbStatus',`Matched ${matched.length} titles from this MDBList to your provider catalog.`,'ok');setTimeout(()=>{modal=null;state.page='home';render()},650)}catch(err){setStatus('#mdbStatus',err.message||String(err),'err')}});
}

window.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal){modal=null;render()}if((e.key==='ArrowRight'||e.key==='ArrowLeft'||e.key==='ArrowDown'||e.key==='ArrowUp')&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)){const focusables=[...document.querySelectorAll('button:not([hidden]),[tabindex="0"]')].filter(x=>x.offsetParent!==null);const i=focusables.indexOf(document.activeElement);if(i>=0){e.preventDefault();focusables[(i+(e.key==='ArrowRight'||e.key==='ArrowDown'?1:-1)+focusables.length)%focusables.length].focus()}}});
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
